#!/bin/sh

# CSS style
SETUPFILE="https://raw.githubusercontent.com/fneissen/org-html-themes/master/org/theme-readtheorg.setup"
echo "#+SETUPFILE: ${SETUPFILE}" > index.org

emacs index.org \  # Temporary org file with setup configuration
      --batch -Q \
      --load emacs-minimal-html-export-init.el \
      -f org-html-export-to-html --kill

# The output directory is uploaded to the GitHub pages repository.
mkdir ~/.github/output
mv index.html ~/.github/output
