#!/bin/sh

# CSS style
touch index.org
SETUPFILE="https://fneissen.github.io/org-html-themes/org/theme-readtheorg.setup"
echo "#+SETUPFILE: ${SETUPFILE}" >> index.org
cat ../../.config/emacs/README.org >> index.org

#emacs --batch -l org --eval '(org-babel-tangle-file "~/.config/emacs/README.org")'
emacs index.org --batch -Q \
      -l emacs-minimal-html-export-init.el \
      -f org-html-export-to-html --kill

# The output directory is uploaded to the GitHub pages repository.
mkdir -p ../output
mv index.html ../output
rm index.org
