set nocompatible

"" Vundle
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
source ~/.vim/plugins.vim
call vundle#end()
filetype plugin indent on

source ~/.vim/remaps.vim

syntax enable
set background=dark
colorscheme solarized

set cursorline
set number
set showmatch
set wrap
set textwidth=0 wrapmargin=0
set showcmd
set autoread

set foldmethod=indent
set foldlevel=10
set tabstop=4
set softtabstop=4
set shiftwidth=4
set textwidth=79
set expandtab
set autoindent

set fileformat=unix
set encoding=utf-8

" NERDTree
" Start automatically when vim is started with no arguments
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
let NERDTreeQuitOnOpen = 1
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1

" Stop running pylint checks when files are saved
let g:pymode_lint_write = 0
