#!/bin/sh

export PATH=$PATH:~/.local/bin:~/.scripts

# Default programs
export EDITOR="nvim"
export VISUAL="nvim"
export BROWSER="qutebrowser"
export READER="zathura"

# XDG standard directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# Config locations
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# Data locations
export STACK_ROOT="$XDG_DATA_HOME/stack"
export HISTFILE="$XDG_DATA_HOME/bash/history"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"

# Cache locations
export LESSHISTFILE=-
export ICEAUTHORITY="$XDG_CACHE_HOME/ICEauthority"
export OCTAVE_HISTFILE="$XDG_CACHE_HOME/octave_hist"
export PYLINTHOME="$XDG_CACHE_HOME/pylint"

# Runtime locations (in /run/user/1000)
export RXVT_SOCKET="$XDG_RUNTIME_DIR/urxvtd"

# Program settings
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'
