name: myXmonad

dependencies:
    - base
    - xmonad
    - xmonad-contrib
    - split
    - fitspec

executables:
    xmonad:
        source-dirs: app
        main:        Main.hs
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall
