name: myXmonad

dependencies:
    - base
    - xmonad
    - xmonad-contrib
    - split
    - fitspec

library:
    source-dirs: src

executables:
    xmonad:
        source-dirs:  app
        main:         Main.hs
        dependencies: myXmonad
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall
