#!/usr/bin/sh

# Get the left volume, right volume or the volume status
get_volume() {

    side="Left"
    field="2"

    case $1 in
        "status") field="4" ;;
        "right") side="Right" ;;
        *) ;;
    esac

    amixer get Master \
        | grep "${side}: " \
        | awk -F'[][]' "{ print \$${field} }"
}

# This script is only designed to work when the left and right volumes are the same
[ `get_volume left` != `get_volume right` ] \
    && notify-send "Warning:" "Left and right volumes differ"

# Notification for incorrect arguments
arg_error() {
    notify-send "Error:" "Invalid argument $1"
}

# Mute or unmute
toggle() {
    amixer set Master toggle
    notify-send "Volume `get_volume status`"
}

# Increase or decrease the volume
change_volume() {
    amixer set Master $2$1 unmute \
        || arg_error $2
    notify-send "Volume `get_volume`"
}

case $1 in
    "toggle") toggle ;;
    "+" | "-") change_volume $1 $2 ;;
    *) arg_error $1 ;;
esac
