#!/usr/bin/sh

# Use the command line argument to define a menu program
MENU_CMD=$1

# List the available colourschemes
options=`colourscheme list`

# Choose one, using the user-defined menu program
choice=`echo "$options" | $MENU_CMD "Change colourscheme to: "`

# Change the colourscheme to the one chosen
colourscheme $choice
