#!/usr/bin/sh

# Program for choosing the file.
# Default: "dmenu -p"
MENU_CMD=${1:-"dmenu -p"}

# Program to display the chosen pdf file.
# Default: zathura
PDF_READER=${2:-"zathura"}

# Hide file extension and certain directory names.
HIDE_DIRS='\(Downloads\|Documents_static\|Documents\)'
FORMATTING="sed s/^${HIDE_DIRS}\///;s/.pdf$//"

# Fix filenames with special characters.
placeholder () {
    [ $1 = "add" ] \
        && sed s/\ /SPACE_PLACEHOLDER/g \
         | sed s/\(/LPARENS_PLACEHOLDER/g \
         | sed s/\)/RPARENS_PLACEHOLDER/g \
        || [ $1 = "remove" ] \
        && sed s/SPACE_PLACEHOLDER/\ /g \
         | sed s/LPARENS_PLACEHOLDER/\(/g \
         | sed s/RPARENS_PLACEHOLDER/\)/g \
        || echo "ERROR: Invalid argument $1 for 'placeholder': expected 'add' or 'remove'"
}

# List all pdfs in $HOME.
FILES=`rg --files \
    --glob '!Projects' \
    --glob '*.pdf' \
    | placeholder add`

# Use $MENU_CMD to choose a file.
CHOICE=`echo $FILES \
    | tr ' ' '\n' \
    | placeholder remove \
    | $FORMATTING \
    | sort \
    | $MENU_CMD 'Read PDF file: ' \
    | placeholder add`

# Find filepath from filename.
FILEPATH=`echo $FILES \
    | tr ' ' '\n' \
    | rg $CHOICE.pdf - \
    | placeholder remove`

# If something is chosen (ESC not pressed), then open it in $PDF_READER.
[ -z $CHOICE ] && notify-send "$FILE not found" \
    || $PDF_READER "$FILEPATH"
