#!/usr/bin/sh

# Command line arguments
MENU_CMD=$1
PDF_READER=$2

# Directory names not to display
HIDE_DIRS='\(Downloads\|Documents_static\)'

# sed command to hide some directory names and the .pdf extension
FORMATTING="sed s/^${HIDE_DIRS}\///;s/.pdf$//"

# List pdfs in home, excluding all the annoying ones installed by pip in Projects
FILES=`rg --files --glob '!Projects' --glob '*.pdf'`
FILES_LIST=`echo $FILES | sed 's/ /\\\n/g'`

# Use $MENU_CMD to choose a file from the scripts directory
CHOICE=`echo $FILES_LIST | $FORMATTING | sort | $MENU_CMD 'Read PDF: '`

# Find filepath from filename
FILE=`echo $FILES_LIST | rg ${CHOICE}.pdf -`

# If something is chosen (ESC not pressed), then edit it
ERROR='notify-send ${FILE} not found'
[ -z $CHOICE ] || $PDF_READER $FILE
