#+TITLE: My scripts
#+STARTUP: overview

Here is a small collection of shell scripts which I have written to automate some common tasks. They should all be POSIX-compliant and therefore usable with a faster shell such as =dash=.

* System

- =adjust-volume=

  This is called by XMonad whenever I want, but can also be used to control the speakers from the command line.
  I can use =adjust-volume toggle= to toggle mute, and =adjust-volume +n= or =adjust-volume -n= to increase or decrease the volume by a certain amount =n=.

- =set-xmonad=

  One downside to tiling window managers is that they don't tend to do much out of the box. I run this on every log-in to XMonad, as running it automatically caused some issues. This script does two things:

  1. It sets up my keyboard. I like to map Caps Lock to Hyper and the space bar (when held) to an additional Super (Windows) key, allowing me to define more keyboard shortcuts and use them with greater comfort. I also map a single tapped Caps Lock to the contortionist combination Control + Escape so that I can map it to open an applications menu.

  2. It sets up my monitors. By default, any external monitors I plug into my laptop simply mirror the laptop display. Depending on an optional argument =l= or =r= (defaulting to =r=), it sets up the monitor as an additional screen to the left or right of my laptop. It also halves the resolution of my laptop so that everything appears the same size.

* Menus

Many of these scripts are based around menus. I can hit a certain key combination to run a script, which gives me a menu and an action based on the option I select. The program used to display the menu depends on an argument. I usually use =rofi=, and therefore pass =rofi -dmenu -i -p= as the argument.

- =menu-change-colourscheme=: selects and applies a systemwide (alacritty and neovim) colourscheme using the =colourscheme= script.
- =menu-edit-config=: opens the selected config file in a text editor specified by the second argument.
- =menu-edit-script=

  Displays a list of all files in my =.scripts= directory. The selected file is opened in the text editor specified by the second argument.
  
- =menu-read-pdf=

  Displays a list of PDF files on my system. The selected file is opened in Zathura or an alternative text editor specified by the second argument. The list of PDF files is automatically generated by searching my =Downloads= and =Documents= directories each time the script is run. Particular effort was made to nicely display files without extensions or common directory names, as well as to support filenames containing whitespace. I use this script many times a day when working.

* Other

- =dzen2-display-cheatsheet=

  This script takes as input the list of keyboard shortcuts generated by XMonad, formats them, and displays them nicely in a =dzen2= instance.
